# Character Classification with MNIST

We begin by following a tutorial on here:https://medium.com/tebs-lab/how-to-classify-mnist-digits-with-different-neural-network-architectures-39c75a0f03e3

Useful code from now deleted notebook. Use to find key with lowest value from dictionary:

In [ ]:
nodeWithMinError = min(results, key=lambda y: abs(results[y]))
nodeWithMinError

### Setup

Import the data

In [6]:
import keras
from keras.datasets import mnist

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [2]:
print("Training data shape: ", x_train.shape) # 60k images, each 28x28 pixels
print("Test data shape: ", x_test.shape) # 10k images, each 28x28 pixels

Training data shape:  (60000, 28, 28)
Test data shape:  (10000, 28, 28)


Flatten the images

In [4]:
image_vector_size = 28*28
x_train = x_train.reshape(x_train.shape[0], image_vector_size)
x_test = x_test.reshape(x_test.shape[0], image_vector_size)

### One-Hot Encoding

We implement one-hot encoding to binerise the catergories. 9 is no longer higher than 1. Predicting 8 when is should be 9 is no better than predicting 7. One-hot encoding vectorises the possible outputs to mean the prediction will be 1 (the hot bit), and the rest will be 0.

Convert to one-hot vectors using the to_categorical function

In [3]:
num_classes = 10

In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [8]:
print("First 5 training labels as one-hot encoded vectors:\n", y_train[:5])

First 5 training labels as one-hot encoded vectors:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


The above is the one-hot version of: [5, 0, 4, 1, 9]